spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: true
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
  datasource:
    url: 'jdbc:mariadb://localhost:3306/reactive'
    username: 'reactive'
    password: 'reactive'
    name: 'reactive'
    initialization-mode: always
server:
  port: 8080